package com.campinggearrental.web;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.campinggearrental.model.*;
import com.campinggearrental.service.*; import com.campinggearrental.repository.RentalOrderRepository;
import com.campinggearrental.state.RentedState;
import java.math.BigDecimal; import java.sql.SQLException; import java.time.LocalDate; import java.util.List;
import org.junit.jupiter.api.*; import org.springframework.test.web.servlet.*; import org.springframework.test.web.servlet.setup.MockMvcBuilders; import org.springframework.web.servlet.view.InternalResourceViewResolver;
class CheckoutWebControllerTest {
 private StubCheckout checkout; private MockMvc mvc; private RentalOrder order;
 @BeforeEach void setUp(){checkout=new StubCheckout();InternalResourceViewResolver v=new InternalResourceViewResolver();v.setPrefix("classpath:/templates/");v.setSuffix(".html");mvc=MockMvcBuilders.standaloneSetup(new CheckoutWebController(checkout,new PricingService())).setViewResolvers(v).build();order=order();}
 @Test void lookupRenders()throws Exception{mvc.perform(get("/checkout")).andExpect(status().isOk()).andExpect(view().name("checkout/lookup"));}
 @Test void blankLookupDoesNotCallService()throws Exception{mvc.perform(post("/checkout/load").param("rentalId"," ")).andExpect(redirectedUrl("/checkout"));assertEquals(0,checkout.loads);}
 @Test void lookupRedirectsToRentalDetailWithFeedback()throws Exception{mvc.perform(post("/checkout/load").param("rentalId"," R1 ")).andExpect(redirectedUrl("/checkout/R1")).andExpect(flash().attribute("success","Rental order loaded."));}
 @Test void detailExposesPersistedOrderAndSnapshot()throws Exception{checkout.order=order;mvc.perform(get("/checkout/R1")).andExpect(status().isOk()).andExpect(view().name("checkout/detail")).andExpect(model().attribute("order",order)).andExpect(model().attribute("rentalDays",5L));assertEquals(1,checkout.loads);assertEquals(new BigDecimal("100.00"),order.getDetails().getFirst().getUnitPrice());}
 @Test void refreshDelegatesAndRedirects()throws Exception{mvc.perform(post("/checkout/R1/refresh")).andExpect(redirectedUrl("/checkout/R1"));assertEquals(1,checkout.refreshes);}
 @Test void serviceFailureRedirectsSafely()throws Exception{checkout.failure=true;mvc.perform(get("/checkout/missing")).andExpect(redirectedUrl("/checkout"));}
 @Test void paymentDelegatesAndPreservesOrderData()throws Exception{checkout.order=order;BigDecimal subtotal=order.getSubtotal(),discount=order.getDiscount(),total=order.getTotal(),unitPrice=order.getDetails().getFirst().getUnitPrice();Object state=order.getCurrentState();int quantity=order.getDetails().getFirst().getQuantity();mvc.perform(post("/checkout/R1/pay")).andExpect(redirectedUrl("/checkout/R1")).andExpect(flash().attribute("success","Payment confirmed."));assertEquals(1,checkout.payments);assertEquals(PaymentStatus.PAID,order.getPaymentStatus());assertEquals(state,order.getCurrentState());assertEquals(subtotal,order.getSubtotal());assertEquals(discount,order.getDiscount());assertEquals(total,order.getTotal());assertEquals(unitPrice,order.getDetails().getFirst().getUnitPrice());assertEquals(quantity,order.getDetails().getFirst().getQuantity());}
 @Test void paidPaymentIsRejectedSafely()throws Exception{order.setPaymentStatus(PaymentStatus.PAID);checkout.order=order;mvc.perform(post("/checkout/R1/pay")).andExpect(redirectedUrl("/checkout/R1")).andExpect(flash().attribute("error","Payment could not be confirmed."));assertEquals(1,checkout.payments);assertEquals(PaymentStatus.PAID,order.getPaymentStatus());}
 @Test void paymentTemplateShowsActionOnlyForUnpaidOrders()throws Exception{String template=new String(getClass().getResourceAsStream("/templates/checkout/detail.html").readAllBytes());assertEquals(true,template.contains("th:if=\"${order.paymentStatus.name() == 'UNPAID'}\""));assertEquals(true,template.contains("/pay|}\""));assertEquals(true,template.contains("th:if=\"${order.paymentStatus.name() == 'PAID'}\""));}
 private static RentalOrder order(){RentalDetail d=new RentalDetail();d.setEquipmentId("EQ1");d.setQuantity(2);d.setUnitPrice(new BigDecimal("100.00"));RentalOrder o=new RentalOrder();o.setId("R1");o.setCustomerId("C1");o.setRentalDate(LocalDate.of(2026,1,1));o.setExpectedReturnDate(LocalDate.of(2026,1,6));o.setDetails(List.of(d));o.setCurrentState(new RentedState());o.setPaymentStatus(PaymentStatus.UNPAID);o.setSubtotal(new BigDecimal("1000.00"));o.setDiscount(new BigDecimal("100.00"));o.setTotal(new BigDecimal("900.00"));return o;}
 private static class StubCheckout extends PersistedCheckoutService { RentalOrder order; boolean failure; int loads,refreshes,payments; StubCheckout(){super(new RentalOrderRepository(){public void insert(RentalOrder o){}public java.util.Optional<RentalOrder> findById(String i){return java.util.Optional.empty();}public java.util.List<RentalOrder> findAll(){return List.of();}public void update(RentalOrder o){}},new CheckoutService(new RentalPricingAdapter(new PricingService())));} public RentalOrder load(String id)throws SQLException{loads++;if(failure)throw new SQLException("internal");return order;} public RentalOrder refreshPricing(String id){refreshes++;return order;} public RentalOrder confirmPayment(String id){payments++;if(order.getPaymentStatus()!=PaymentStatus.UNPAID)throw new IllegalStateException("only unpaid orders can be paid");order.setPaymentStatus(PaymentStatus.PAID);return order;} }
}
